apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APP_NAME}
  namespace: ${NAMESPACE}
  annotations:
    kubernetes.io/change-cause: "Image update trigger"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ${APP_NAME}
  template:
    metadata:
      labels:
        app: ${APP_NAME}
      annotations:
        rollme: "$(date +%s)"
        linkerd.io/inject: enabled
    spec:
      containers:
      - name: ${CONTAINER_NAME}
        image: ${IMAGE_REPOSITORY}:${IMAGE_TAG}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: SITE_ORIGIN
          value: "${SITE_ORIGIN}"

      imagePullSecrets:
      - name: ${IMAGE_PULL_SECRET}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: ${APP_NAME}
  namespace: ${NAMESPACE}
spec:
  selector:
    app: ${APP_NAME}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${APP_NAME}-ingress
metadata:
  name: ${APP_NAME}-ingress
  namespace: ${NAMESPACE}
spec:
  rules:
  - host: ${INGRESS_HOST}
    http:
      paths:
      - path: ${INGRESS_PATH}
        pathType: ${INGRESS_PATH_TYPE}
        backend:
          service:
            name: ${APP_NAME}
            port:
              number: ${SERVICE_PORT}
